"use client"

import { motion } from "framer-motion"
import { X } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Textarea } from "@/components/ui/textarea"
import { useState, useEffect } from "react"
import { Progress } from "@/components/ui/progress"

interface WorkflowOutputProps {
  workflow: { id: string; name: string }
  onClose: () => void
}

export function WorkflowOutput({ workflow, onClose }: WorkflowOutputProps) {
  const [output, setOutput] = useState("")
  const [showOutput, setShowOutput] = useState(false)
  const [progress, setProgress] = useState(0)

  // Sample outputs based on workflow type
  const legalWorkflowOutput = `# Samsung Legal & Compliance Analysis
## Comprehensive Report Generated by AI Agent Workflow

### Contract Summarizer Analysis
The Contract Summarizer agent has analyzed Samsung's key supplier agreements, partnership contracts, and licensing arrangements to identify critical obligations, risks, and opportunities:

**Supply Chain Agreements Review:**
1. Samsung's component supplier contracts contain variable pricing mechanisms that could be optimized to reduce costs by an estimated 4-7% through renegotiation of volume discount thresholds.

2. Force majeure clauses in 68% of critical supplier contracts lack specific provisions for pandemic-related disruptions, creating potential vulnerability as demonstrated during recent global supply chain challenges.

3. Sustainability requirements in supplier agreements vary significantly by region, with European contracts containing the most stringent environmental compliance language. Standardization opportunity exists to align with Samsung's global ESG commitments.

4. Termination notice periods range from 30-180 days across the supplier portfolio, with strategic components requiring the longest notice periods. This creates operational planning challenges that could be addressed through standardization.

5. Intellectual property provisions in 23% of supplier agreements contain ambiguous language regarding improvements and derivative technologies, potentially limiting Samsung's ability to innovate based on supplier components.

**Partnership & Licensing Analysis:**
1. Technology licensing agreements for Samsung's display technologies represent approximately $428M in annual revenue, with renewal negotiations for 38% of this portfolio occurring within the next 18 months.

2. Cross-licensing arrangements with three major technology partners contain most-favored-nation clauses that require careful management to avoid unintended rate reductions.

3. Joint venture agreements in emerging markets contain governance provisions that may limit operational flexibility as these markets mature, with amendment opportunities identified in 4 key agreements.

4. Distribution partnership agreements in 12 markets lack clear performance metrics and termination rights, potentially limiting Samsung's ability to optimize channel strategy.

5. Patent licensing costs have increased 12% year-over-year, exceeding budget projections and creating margin pressure in the mobile device division.

**Risk Assessment & Recommendations:**
The Contract Summarizer has categorized contractual risks by potential financial impact and likelihood, identifying the following priority areas for legal department focus:

1. **High Impact/High Likelihood:**
   - Supplier force majeure provisions
   - Patent licensing cost increases
   - Ambiguous IP improvement rights

2. **High Impact/Medium Likelihood:**
   - Most-favored-nation trigger events
   - Joint venture governance limitations

3. **Medium Impact/High Likelihood:**
   - Variable pricing optimization opportunities
   - Distribution agreement performance metrics

Recommended actions include developing standardized force majeure language addressing modern supply chain risks, conducting a comprehensive patent licensing strategy review, and implementing a contract lifecycle management system to provide better visibility into renewal timelines and obligation tracking.`

  const defaultOutput = `# Custom Workflow Analysis for Samsung
## Comprehensive Report Generated by AI Agent Workflow

This custom workflow has analyzed Samsung's market position, competitive landscape, and strategic opportunities. The analysis leverages multiple AI agents working in concert to provide a comprehensive view of Samsung's current situation and future potential.

### Market Position Analysis
Samsung continues to maintain a strong global market position across multiple product categories:

1. In the smartphone market, Samsung holds approximately 21% global market share, positioning it as the leading Android device manufacturer and second overall behind Apple.

2. In the television segment, Samsung leads with approximately 33% of the global market for premium TVs, with particular strength in the QLED and large-format categories.

3. In home appliances, Samsung has achieved 19% market share globally, with stronger positions in refrigeration (23%) and laundry (21%) categories.

4. In semiconductor manufacturing, Samsung remains a dominant player with approximately 12% of the global market, competing primarily with TSMC in the foundry business.

5. In memory chips, Samsung maintains leadership with approximately 44% of the DRAM market and 35% of the NAND flash market.

These strong market positions provide Samsung with scale advantages and ecosystem opportunities, but also create challenges in maintaining growth rates and defending against both premium and value-oriented competitors.

### Competitive Landscape Assessment
The competitive environment facing Samsung continues to evolve across its business segments:

**Mobile Devices:**
- Apple maintains premium positioning with higher average selling prices and stronger ecosystem lock-in
- Chinese manufacturers (Xiaomi, Oppo, Vivo) continue to pressure Samsung's mid-range offerings with aggressive pricing
- Google's Pixel devices, while lower volume, establish Android feature benchmarks
- Emerging foldable competition from multiple manufacturers in Samsung's pioneering category

**Consumer Electronics:**
- LG competes directly in premium TV segments with OLED technology contrasting with Samsung's QLED approach
- Sony maintains premium positioning with strong content integration
- TCL and Hisense provide value competition with improving quality
- Specialized audio brands partner with TV manufacturers to challenge Samsung's integrated audio approach`

  // Replace the entire useEffect for the timer with this simplified version that guarantees the output will show
  useEffect(() => {
    // Start with progress at 0
    setProgress(0)

    // Show loading state immediately
    setShowOutput(false)

    // Set up timer to increment progress and show output after completion
    const timer = setInterval(() => {
      setProgress((prevProgress) => {
        const newProgress = prevProgress + 1

        // When we reach 100%, clear the interval and show the output
        if (newProgress >= 100) {
          clearInterval(timer)
          setShowOutput(true)

          // Set the appropriate output based on workflow type
          if (workflow.id === "legal-workflow") {
            setOutput(legalWorkflowOutput)
          } else {
            setOutput(defaultOutput)
          }

          return 100
        }

        return newProgress
      })
    }, 1000) // Update every second for 100 seconds

    return () => {
      clearInterval(timer)
    }
  }, [workflow.id]) // Re-run this effect if the workflow changes

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      exit={{ opacity: 0, y: 20 }}
      className="absolute bottom-4 left-4 z-40 w-96 rounded-lg glass-card shadow-xl overflow-hidden"
    >
      <div className="flex items-center justify-between border-b border-border/50 p-3 backdrop-blur-sm">
        <h3 className="font-heading font-medium">Workflow Output</h3>
        <motion.button
          whileHover={{ scale: 1.1, backgroundColor: "hsl(var(--accent))" }}
          whileTap={{ scale: 0.9 }}
          onClick={onClose}
          className="rounded-full p-1 hover:bg-accent transition-colors duration-200"
        >
          <X size={16} />
        </motion.button>
      </div>

      <div className="custom-scrollbar h-80 overflow-y-auto p-3 bg-background/50">
        {!showOutput ? (
          <div className="flex flex-col items-center justify-center h-full space-y-4">
            <div className="text-center">
              <h3 className="text-lg font-medium mb-2">Processing Workflow</h3>
              <p className="text-sm text-muted-foreground mb-4">
                AI agents are analyzing data and generating results...
              </p>
              <Progress value={progress} className="w-64 h-2" />
              <p className="text-xs text-muted-foreground mt-2">{progress}% complete</p>
            </div>
          </div>
        ) : (
          <Textarea
            value={output}
            onChange={(e) => setOutput(e.target.value)}
            className="w-full h-full bg-transparent border-none shadow-none focus-visible:ring-0 resize-none"
            readOnly
          />
        )}
      </div>

      <div className="border-t border-border/50 p-3 bg-card/50 backdrop-blur-sm">
        <Button variant="outline" className="w-full" onClick={onClose}>
          Close
        </Button>
      </div>
    </motion.div>
  )
}

